config/routes.rb
Scrappy::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :emails, only: [:index, :show, :destroy], path: 'offer' do
    get 'raw', on: :member
  end
  
  root :to => 'emails#index'

end

app/models/account.rb
class Account < ActiveRecord::Base
  has_many :emails, dependent: :nullify
  attr_accessible :email, :password

  def to_s
    self.email
  end
end

# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  email      :string(255)
#  password   :string(255)
#  created_at :datetime
#

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

# == Schema Information
#
# Table name: admin_users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null, indexed
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)      indexed
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

app/models/email.rb
# coding: utf-8

require 'gmail'

class Email < ActiveRecord::Base
  belongs_to :account
  belongs_to :site
  attr_accessible :from, :subject, :body, :slug

  extend FriendlyId
  friendly_id :subject, use: :slugged

  include PgSearch
  pg_search_scope :search_by_subject, :against => :subject

  validates :from, :subject, :body, :slug, presence: true

  before_create :assign_site, :assign_cover_image

  scope :latest, order('created_at DESC')
  scope :recent, lambda{|limit| order('created_at DESC').limit(limit) }

  def self.post_to_twitter
    email = Email.where("created_at > ?", 10.minutes.ago).first
    email.post_to_twitter if email
  end

  # Clean email from account's email, unsubscribe links, ...
  def clean_inner_body
    # remove account's email
    stop_email = [self.account.email, self.account.email.split('@').first].join('|')
    body = self.body.gsub(/#{stop_email}/i, '')

    html = Nokogiri::HTML(body)

    # remove all stop words links
    stop_words = %w(subscri here view link online account mobile why\ did friend browser manage preference)
    stop_words.each do |word|
      i = search_text(html, word)
      i.xpath('./ancestor::a').remove
      i.remove
    end

    # remove css styles 
    html.css('style').remove
    # link should be opened in new browser's tab
    html.css('a, area').each {|link| link['target'] = '_blank'}

    # the email can have two body tag (it's email's template error)
    html.css('body').map(&:inner_html).join('')
  end

  def post_to_twitter
    message = "##{self.site.title} #{self.subject} #{Rails.application.routes.url_helpers.email_url(self, host: 'wiclone.com')}"
    Twitter.update(message)
  end

  # Find best image for the email
  def find_cover_image
    images = []
    Nokogiri::HTML(self.body).css('img').each do |img|
      if img['src']
        size = FastImage.size(img['src']) rescue nil
        images << {src: img['src'], 
                   w: size.first,
                   h: size.last,
                   q: (size.first - size.last).abs, # difference between width and height
                   s: size.first * size.last # square
                  } if size
      end
    end
    # sort by q by asceding
    images.sort!{|a,b| a[:q] <=> b[:q]}
    # select images with square more than 10000 (100x100)
    images = images.select{|image| image[:s] > 10000 }
    images.first
  end

  def assign_cover_image
    image = self.find_cover_image
    if image
      self.cover_image = image[:src]
      self.cover_image_width = image[:w]
      self.cover_image_height = image[:h]
    end
  end

  private
  def assign_site
    self.site = Site.find_or_create_by_email(self.from)
  end

  def search_text(html, text)
    html.search("//*[contains(translate(text(),'ABCDEFGHIJKLMNOPQRSTUVWXYZ','abcdefghijklmnopqrstuvwxyz'),'#{text}')]")
  end

end

# == Schema Information
#
# Table name: emails
#
#  id                 :integer          not null, primary key
#  account_id         :integer          indexed
#  site_id            :integer
#  from               :string(255)      not null
#  subject            :string(500)      not null
#  body               :text             not null
#  slug               :string(500)      not null, indexed
#  created_at         :datetime
#  cover_image        :string(255)
#  cover_image_width  :integer
#  cover_image_height :integer
#

app/models/possible_site.rb
class PossibleSite < ActiveRecord::Base
  attr_accessible :name, :category, :done, :yahoo_url, :yahoo_products_url, :rating, :ratings_count, :reviews_count
  
  validates_presence_of :name
  validates_uniqueness_of :name, uniq: true

  before_create :assign_url

  def assign_url
    self.url = self.name.downcase.strip.gsub(/\s/m, '')
    self.url << '.com' unless name =~ /\.com|\.net|\.us/
  end
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :emails, dependent: :delete_all
  
  attr_accessible :title, :url, :email, :slug, :approved
  validates :title, :url, :email, presence: true
  
  before_validation :assign_title_and_url, on: :create

  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :not_approved, where(approved: false)

  private
  def assign_title_and_url
    splitted = self.email.split('@').last.split('.').reverse[0..1].reverse
    self.title = splitted.first
    self.url = splitted.join('.')
  end
end

# == Schema Information
#
# Table name: sites
#
#  id    :integer          not null, primary key
#  title :string(255)      not null
#  url   :string(255)      not null
#  email :string(255)      not null, indexed
#  slug  :string(255)      not null, indexed
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_filter :authenticate_admin_user!, only: [:raw, :destroy]
  before_filter :find_email, only: [:show, :raw, :destroy]

  def index
    @emails = Email.joins(:site).where("sites.approved = true").latest
    if params[:search]
      if params[:search].starts_with?('site:')
        @emails = @emails.where("sites.slug = ?", params[:search].split(':').last)
      else
        @emails = @emails.search_by_subject(params[:search])
      end
    end
    @emails = @emails.page(params[:page]).per(50)

    render(partial: 'board_items', layout: nil) if request.xhr?
  end

  def show
    render(layout: nil) if request.xhr?
  end

  def raw
    render text: @email.body, layout: nil
  end

  def destroy
    @email = Email.find(params[:id])
    @email.destroy

    redirect_to root_path
  end

  private
  def find_email
    @email = Email.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
  def cover_image_tag(email, max_width = 200)
    if email.cover_image.present?
      width = email.cover_image_width || 200
      height = email.cover_image_height || 200
      if width > max_width
        height = height * max_width / width
        width  = max_width
      end
      
      # image_tag email.cover_image, width: width, height: height
      # Use raw html to exclude error ActionView::Template::Error ( isn't precompiled)
      raw("<img src='#{email.cover_image}' width='#{width}' height='#{height}'")
    else
      image_tag 'default-cover.jpg', width: 200, height: 200
    end
  end

  def search_link_to(title, email, options={})
    query = "site:#{email.site.slug}"
    options.reverse_merge!({'data-search' => query, class: 'search-link'})
    
    link_to title, root_path(search: query), options
  end
end

app/views/admin/dashboard/_report.html.slim
#report-chart(style="height: 300px")

javascript:
  $(function () {
    new Highcharts.Chart({
      chart: { renderTo: 'report-chart', type: 'column' },
      title: { text: 'Numbers Emails By Day' },
      xAxis: { 
        type: 'datetime',
        dateTimeLabelFormats: { 
                    month: '%e. %b',
                    year: '%b'
                  }
      },
      yAxis: {
        title: { text: 'Total' }
      },
      tooltip: {
          formatter: function() {
            return '<b>'+ (new Date(this.x)).toDateString() +'</b><br/>'+ this.y;
          }
      },
      plotOptions: {
              column: {
                pointWidth: 7,
                borderWidth: 1
              }
            },
      series: [
        {
          data: #{raw Report.numbers_emails_by_day.map{|i| [DateTime.parse(i.day).to_i * 1000, i.total.to_i] }.to_json }}
      ]
    });
  });

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    = display_meta_tags site: 'Subscry', reverse: true
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag "application"
    = javascript_include_tag "application" 
    = favicon_link_tag
    /[ if lt IE 9 ]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"
    = csrf_meta_tags
    = yield :head
    = render 'shared/google_analytics'
  body
    .menu
      .menu-inner
        = link_to root_path, class: 'brand' do
          | Newsletter's Home
          span Subscribe to newsletters by ONE click
        = form_tag root_path, method: 'get', id: 'search-form', class: 'menu-search' do 
          = text_field_tag :search, params[:search], class: 'search-query', placeholder: 'Search'
      = render 'shared/admin_menu'
    = yield

app/views/shared/_admin_menu.html.slim
- if current_admin_user
  #admin-menu
    ul
      li= link_to 'Admin Panel', admin_root_path
      = yield :admin_menu

app/views/shared/_google_analytics.html.slim
- if Rails.env.production?
  javascript:
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-36115803-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();